import packageJson from "../../package.json" with { type: "json" }

export const LIMITS = {
  MAX_EMBED_SIZE: 6000,
  MAX_EMBED_DESCRIPTION: 4096,
  MAX_EMBED_TITLE: 256,
  MAX_EMBED_FIELDS: 25,
  MAX_EMBED_FIELD_NAME: 256,
  MAX_EMBED_FIELD_VALUE: 1024,
  MAX_EMBED_FOOTER_TEXT: 2048,
  MAX_EMBED_AUTHOR_NAME: 256,
  MAX_MODAL_TITLE: 45,
  MAX_COMMAND_NAME: 32,
  MIN_COMMAND_NAME: 1,
  MAX_COMMAND_DESCRIPTION: 100,
  MIN_COMMAND_DESCRIPTION: 1,
  MAX_COMMAND_OPTIONS: 25,
  MAX_COMMAND_OPTION_NAME: 32,
  MIN_COMMAND_OPTION_NAME: 1,
  MAX_COMMAND_OPTION_DESCRIPTION: 100,
  MIN_COMMAND_OPTION_DESCRIPTION: 1,
  MAX_COMMAND_OPTION_CHOICES: 25,
  MAX_COMMAND_OPTION_CHOICE_NAME: 100,
  MIN_COMMAND_OPTION_CHOICE_NAME: 1,
  MAX_COMMAND_OPTION_CHOICE_VALUE: 100,
  MIN_COMMAND_OPTION_CHOICE_VALUE: 1,
  MAX_ACTION_ROW_BUTTONS: 5,
  MAX_MODAL_COMPONENTS: 5,
  MAX_BUTTON_LABEL: 80,
  MAX_BUTTON_CUSTOM_ID: 100,
  MAX_DROPDOWN_CUSTOM_ID: 100,
  MAX_DROPDOWN_OPTIONS: 25,
  MAX_DROPDOWN_PLACEHOLDER: 150,
  MIN_MIN_DROPDOWN_VALUES: 0,
  MAX_MIN_DROPDOWN_VALUES: 25,
  MAX_TEXT_INPUT_LABEL: 45,
  MAX_MESSAGE_CONTENT: 2000,
  MAX_TEXT_INPUT_VALUE: 4000,
  MAX_TEXT_INPUT_PLACEHOLDER: 100,
  MAX_MESSAGE_EMBEDS: 10,
  MAX_MESSAGE_COMPONENTS: 5,
}

export enum INTERACTION_TYPES {
  PING = 1,
  APPLICATION_COMMAND = 2,
  MESSAGE_COMPONENT = 3,
  APPLICATION_COMMAND_AUTOCOMPLETE = 4,
  MODAL_SUBMIT = 5,
}

export enum COMPONENT_TYPES {
  ACTION_ROW = 1,
  BUTTON = 2,
  STRING_SELECT = 3,
  TEXT_INPUT = 4,
  USER_SELECT = 5,
  ROLE_SELECT = 6,
  MENTIONABLE_SELECT = 7,
  CHANNEL_SELECT = 8,
  SECTION = 9,
  TEXT_DISPLAY = 10,
  THUMBNAIL = 11,
  MEDIA_GALLERY = 12,
  FILE = 13,
  SEPARATOR = 14,
  CONTAINER = 17,
  LABEL = 18,
  FILE_UPLOAD = 19,
  RADIO_GROUP = 21,
  CHECKBOX_GROUP = 22,
  CHECKBOX = 23,
}

export enum INTERACTION_CALLBACK_TYPES {
  PONG = 1,
  CHANNEL_MESSAGE_WITH_SOURCE = 4,
  DEFERRED_CHANNEL_MESSAGE_WITH_SOURCE = 5,
  DEFERRED_UPDATE_MESSAGE = 6,
  UPDATE_MESSAGE = 7,
  APPLICATION_COMMAND_AUTOCOMPLETE_RESULT = 8,
  MODAL = 9,
  PREMIUM_REQUIRED = 10,
}

export enum TEXT_INPUT_STYLES {
  SHORT = 1,
  PARAGRAPH = 2,
}

export const MESSAGE_FLAGS = {
  CROSSPOSTED: 1 << 0,
  IS_CROSSPOST: 1 << 1,
  SUPPRESS_EMBEDS: 1 << 2,
  SOURCE_MESSAGE_DELETED: 1 << 3,
  URGENT: 1 << 4,
  HAS_THREAD: 1 << 5,
  EPHEMERAL: 1 << 6,
  LOADING: 1 << 7,
  FAILED_TO_MENTION_SOME_ROLES_IN_THREAD: 1 << 8,
  SUPPRESS_NOTIFICATIONS: 1 << 12,
  IS_VOICE_MESSAGE: 1 << 13,
  HAS_SNAPSHOT: 1 << 14,
  IS_COMPONENTS_V2: 1 << 15,
} as const

export enum COMMAND_OPTION_TYPES {
  SUB_COMMAND = 1,
  SUB_COMMAND_GROUP = 2,
  STRING = 3,
  INTEGER = 4,
  BOOLEAN = 5,
  USER = 6,
  CHANNEL = 7,
  ROLE = 8,
  MENTIONABLE = 9,
  NUMBER = 10,
  ATTACHMENT = 11,
}

export enum BUTTON_STYLES {
  PRIMARY = 1,
  SECONDARY = 2,
  SUCCESS = 3,
  DANGER = 4,
  LINK = 5,
  PREMIUM = 6,
}

export const CHAMELEON_VERSION = packageJson.version
export const CHAMELEON = packageJson.name